### ISSUE TITLE
Release version 2.0

### ISSUE THREAD

**Issue by pacman82** [blue-yonder/urlquote#9]
Updated the bulid sytem to maturin to keep up with the times (and newer Python Versions). Also switched from travis to GitHub actions. If somebody with appropriate rights would please add a `PYPI_API_TOKEN` secret to the repository and create a (GitHub) release. I no longer work at BY and do not have the rights to do so.

Cheers, Markus

**Comment by bjoernmeier** [comment]
@pacman82 I did trigger the 2.0.0 release but the auth for pypi fails and I did read this too late 🤦 and thought the trigger of the release is the issues. There I lack the power to resolve this, have to check who can fix the credentials.

**Comment by pacman82** [comment]
@bjoernmeier I do not mind bias to action, and nothing bad happend. Personally I would just delete the release and the tag. It is not like anything has been published. We can also just release `3.0` next time.

**Comment by bjoernmeier** [comment]
I already cleaned up. Probably was still too early :D and I thought only the release was required and missed that the Token is the issue. Will see what I can do there.

**Comment by sebastianneubauer** [comment]
can the exact error message still be seen somewhere?

**Comment by sebastianneubauer** [comment]
this one, right?
```25hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         Invalid or non-existent authentication information. See                
         https://pypi.org/help/#invalid-auth for more information.              
Error: Process completed with exit code 1.
```

**Comment by bjoernmeier** [comment]
Sure, the action history is still there https://github.com/blue-yonder/urlquote/actions/runs/3407964540/jobs/5668102955#step:4:235.

Some note: waybe at some place we should change the name of one of the 2 github workflows so that the tests and package build/upload do not have the same name.

**Comment by pacman82** [comment]
@sebastianneubauer The authentication error is no mystery. We need a configured secret by the name of `PYPI_API_TOKEN` which is a valid token to push  a repository for this PyPI User: <https://pypi.org/user/BYPyPi/>

Since this is also the user which publishes `turbodbc` or `kartothek` somebody at BY is likely to have the credentials for this user. `urlquote` has previously been deployed using travis. The GitHub Action for deployment never ran before, it is brand new and I just created it in the hope somebody can configure the secret for it.

**Comment by yogevyuval** [comment]
@sebastianneubauer Any chance you know how to get the `PYPY_API_TOKEN` secret?

**Comment by sebastian-neubauer-by** [comment]
Added a secret with an API token for urlquote in pypi...what do I have to do now?

**Comment by yogevyuval** [comment]
> Added a secret with an API token for urlquote in pypi...what do I have to do now?

As you can see here:
https://github.com/blue-yonder/urlquote/blob/6d760ec49ffe1d1b161ed1616426a9e02cccec32/.github/workflows/publish-wheel.yml#L25

The CI uses a Github Actions secret named PYPY_API_TOKEN to push to pypi. So we need to add the secret to github actions for this repo and then trigger another build

**Comment by sebastian-neubauer-by** [comment]
mmh, failed again:
```
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         Invalid or non-existent authentication information. See                
         https://pypi.org/help/#invalid-auth for more information. 
```

**Comment by yogevyuval** [comment]
> mmh, failed again:
> 
> ```
> WARNING  Error during upload. Retry with the --verbose option for more details. 
> ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
>          Invalid or non-existent authentication information. See                
>          https://pypi.org/help/#invalid-auth for more information. 
> ```

@pacman82 @bjoernmeier any idea?

**Comment by sebastian-neubauer-by** [comment]
ah, copied it from your comment @yogevyuval , but PYPY_API_TOKEN looks like a typo...

**Comment by sebastian-neubauer-by** [comment]
wohoo, seems we have a 2.0 release https://pypi.org/project/urlquote/

**Comment by yogevyuval** [comment]
> ah, copied it from your comment @yogevyuval , but PYPY_API_TOKEN looks like a typo...

Ahhh so sorry! Thanks for the effort!

**Comment by yogevyuval** [comment]
Looks like for some reason the wheel is still not grabbed by pip on python 3.11
![image](https://user-images.githubusercontent.com/962869/200942998-27e0495c-0b5e-4b6b-9713-c8a36613a17b.png)

**Comment by yogevyuval** [comment]
@pacman82 Is this the intended wheel name?
[urlquote-2.0.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/9c/03/3ccc0bb7f8d8f3f06c8d9bd6d08f5b02c78c0d6acbf0d3c806b1fbf63b43/urlquote-2.0.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=196d6275829d4c3df02f6732f6b5ffe4b00ea74def2a66eb9139f01eaff2d0fc)

**Comment by sebastian-neubauer-by** [comment]
strange, worked for me on mac...
<img width="503" alt="Screenshot at Nov 09 22-16-33" src="https://user-images.githubusercontent.com/57490446/200943571-037b25f4-e0ca-4a42-998d-6833adf4284f.png">

**Comment by yogevyuval** [comment]
> strange, worked for me on mac... <img alt="Screenshot at Nov 09 22-16-33" width="503" src="https://user-images.githubusercontent.com/57490446/200943571-037b25f4-e0ca-4a42-998d-6833adf4284f.png">

Doesnt work on python linux docker for some reason
![image](https://user-images.githubusercontent.com/962869/200944335-f0de5fb6-7cc8-4832-b131-203032b33007.png)

**Comment by sebastian-neubauer-by** [comment]
mmh, worked for me in docker as well
`docker run -ti python:3.11.0 bash`
<img width="565" alt="Screenshot at Nov 09 22-23-54" src="https://user-images.githubusercontent.com/57490446/200944856-3269d49e-baf4-41ee-8a9f-ce3b5c64b660.png">

**Comment by yogevyuval** [comment]
> `docker run -ti python:3.11.0 bash`

Tried it on another linux server and it worked.
I think the problem is that I have an M1 mac. Do the new wheels support M1 / linux docker running on M1?

**Comment by pacman82** [comment]
Hello @yogevyuval ,

name is as intended. As you suggested the ManyLinux wheels deployed on PyPI do not work on ARM architectures like M1. To create one we would need a CI runner with OS-X and ARM. AFAIK GitHub does not offer such a build server.

Luckily `urlquote` is easy to build. You only need to go to `rustup.rs` and install the Rust toolchain as proposed by the error message. Then try again to `pip install urlquote`.

Cheers, Markus

**Comment by pacman82** [comment]
> wohoo, seems we have a 2.0 release https://pypi.org/project/urlquote/

Thanks you Sebastian!
